version: '3.8'

services:
  keta-frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_STRAPI_URL: https://admin.ketaakademi.com
        NEXT_PUBLIC_FRONTEND_URL: http://localhost:3000
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_STRAPI_URL=https://admin.ketaakademi.com
      - NEXT_PUBLIC_FRONTEND_URL=http://localhost:3000
    restart: unless-stopped